version: "3"
services:
  rabbit:
    image: "rabbitmq:3.9-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbit-compose-network
    volumes:
      - ./volume:/var/lib/rabbitmq/mnesia
networks:
  rabbit-compose-network:
    driver: bridge
