#for this image to run, it's may require to run this command
#sudo sysctl -w vm.max_map_count=262144
version: '3.1'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    restart: always
    ports:
      - 9200:9200
    ulimits:
      nproc: 262144
      nofile:
        soft: 20000
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2Gi
        reservations:
          cpus: '1'
          memory: 1.5Gi

  # kibana:
  #   image: kibana:7.4.0
  #   ports:
  #     - 5601:5601
